name: Build Vue
on:
  push:
    branches: [ "*" ]
  workflow_dispatch:
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'github-pages' || 'feature-github-pages' }}
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: Create .env file
        run: |
          echo "VITE_SPACE=${{ secrets.CONTENTFUL_SPACE_ID }}" >> .env
          echo "VITE_ACCESS_TOKEN=${{ secrets.CONTENTFUL_CONTENT_DELIVERY_API_KEY }}" >> .env
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
